# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Java CA certificates permissions
# See tmpfiles.d(5) for format

z /opt/zextras/common/etc/java/cacerts 0644 zextras zextras
